# -*- mode: ruby -*-
# # vi: set ft=ruby :

require 'yaml'
servers = YAML.load_file('servers.yaml')

Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/trusty64"

	servers.each do |servers|
		config.vm.define servers["name"] do |srv|
			srv.vm.network "public_network", ip: servers["ip"], bridge: "en1: Wi-Fi (AirPort)"
			srv.vm.provider :virtualbox do |vb|
				vb.name = servers["name"]
				vb.memory = servers["ram"]
				vb.cpus = servers["cpus"]
			end
		end
	end
end