# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = "ubuntu/trusty64" #Ubuntu 14.04
    config.vm.hostname = "UbuntuDev"

    config.vm.network "forwarded_port", guest: 80, host: 50004
    config.vm.network "forwarded_port", guest: 9001, host: 50005

    #config.vm.synced_folder "host_folder", "guest_folder"
    config.vm.provision :shell, :path => "bootstrap.sh"

end
