Vagrant.configure("2") do |config|
    config.vm.box = "dimroc/awsdummy"
        config.vm.provider :aws do |aws, override|
            aws.tags = {"Name" => "YOUR_NAME_PROJECT_NAME",}
            aws.access_key_id = "YOUR_ACCESS_KEY"
            aws.secret_access_key = "AWS_SECRET_KEY"
            aws.keypair_name = "NAME_OF_KEYPAIR"
            aws.region = "us-west-2"
            aws.region_config "us-west-2", :ami => "ami-cd5311fd" #Ubuntu 14.04
            aws.security_groups = [ 'vagrant' ]
            override.ssh.username = "ubuntu"
            override.ssh.private_key_path = "LOCATION_OF_PEM"
    end
    config.vm.provision :shell, :path => "bootstrap.sh"
end